###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.5
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=docker_symfony4
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "8010:3306"
      volumes:
        - ./mysql/data:/docker-entrypoint-initdb.d
      restart: always
    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8100:80"
      restart: always
    php-fpm:
      build: php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      restart: always

